#!/usr/bin/env sh

sleep 0.15

if makoctl mode | grep -e 'do-not-disturb' &> /dev/null; then
  jq -n --unbuffered --compact-output \
    '{"alt": "disabled", "tooltip": "Notifications <span color='"'"'#ee99a0'"'"'>off</span>", "class": "inactive"}'
else
  jq -n --unbuffered --compact-output \
    '{"alt": "enabled", "tooltip": "Notifications <span color='"'"'#a6da95'"'"'>on</span>"}'
fi
